---
- name: Bootstrap server for python support
  raw:  bash -c "test -e /usr/bin/python3 || (apt update && apt install -y python3)"
  changed_when: False

- name: Update system
  apt:
    upgrade: true
    update_cache: true
