---
dependency:
  name: galaxy
driver:
  name: podman 
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-centos:latest}
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
