---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-centos:7}
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
